# Generated by Django 3.1 on 2020-08-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveindiaapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type_of',
            new_name='type_name',
        ),
    ]
