# Generated by Django 3.1 on 2020-08-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveindiaapi', '0002_auto_20200804_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type_name',
            new_name='type_of',
        ),
    ]
